# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import platform_interface_pb2 as platform__interface__pb2


class platform_interfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUpdates = channel.unary_stream(
                '/platform_interface/GetUpdates',
                request_serializer=platform__interface__pb2.InitGetUpdate.SerializeToString,
                response_deserializer=platform__interface__pb2.PlatformUpdate.FromString,
                )
        self.SendCommands = channel.stream_stream(
                '/platform_interface/SendCommands',
                request_serializer=platform__interface__pb2.CommandRequest.SerializeToString,
                response_deserializer=platform__interface__pb2.CommandResponse.FromString,
                )


class platform_interfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommands(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_platform_interfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUpdates,
                    request_deserializer=platform__interface__pb2.InitGetUpdate.FromString,
                    response_serializer=platform__interface__pb2.PlatformUpdate.SerializeToString,
            ),
            'SendCommands': grpc.stream_stream_rpc_method_handler(
                    servicer.SendCommands,
                    request_deserializer=platform__interface__pb2.CommandRequest.FromString,
                    response_serializer=platform__interface__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'platform_interface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class platform_interface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/platform_interface/GetUpdates',
            platform__interface__pb2.InitGetUpdate.SerializeToString,
            platform__interface__pb2.PlatformUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendCommands(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/platform_interface/SendCommands',
            platform__interface__pb2.CommandRequest.SerializeToString,
            platform__interface__pb2.CommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
